- name: create group Jira
  group:
    name: "{{ jira_user }}"
    state: present

- name: create user Jira
  user:
    name: "{{ jira_user }}"
    group: "{{ jira_user }}"

- name: prepare directories
  file:
    path: "{{ item }}"
    owner: "{{ jira_user }}"
    group: "{{ jira_user }}"
    mode: "0755"
    state: "directory"
  with_items:
    - "{{ jira_home }}"
    - "{{ jira_install }}"

- name: download package
  get_url:
    url: "{{ jira_url }}"
    dest: "/tmp/{{ jira_archive }}"
    checksum: "{{ jira_checksum }}"

- name: unarchive package
  shell: |
    tar zxvf /tmp/{{ jira_archive }} -C {{ jira_install }} --strip-components=1
    chown -Rf {{ jira_user }}:{{ jira_user }} {{ jira_install }}
  args:
    creates: "{{ jira_install }}/bin/start-jira.sh"
  notify: restart jira

- name: unarchive mysql connector package
  unarchive:
    remote_src: yes
    src: "{{ jira_mysql_connector_url }}"
    dest: "/tmp"
    group: "{{ jira_user }}"
    owner: "{{ jira_user }}"

- name: move mysql connector package
  shell: |
    mv /tmp/mysql-connector-java-{{ jira_mysql_connector_version }}/mysql-connector-java-{{ jira_mysql_connector_version }}.jar {{ jira_install }}/lib
    chmod 0444 {{ jira_install }}/lib/mysql-connector-java-{{ jira_mysql_connector_version }}.jar
    chown {{ jira_user }}:{{ jira_user }} {{ jira_install }}/lib/mysql-connector-java-{{ jira_mysql_connector_version }}.jar
  args:
    creates: "{{ jira_install }}/lib/mysql-connector-java-{{ jira_mysql_connector_version }}.jar"
  notify: restart jira

- name: Create systemd unit file
  template:
    src: jira.service.j2
    dest: /etc/systemd/system/jira.service
    owner: root
    group: root
    mode: 0744

- name: Create server config file
  template:
    src: server.xml.j2
    dest: "{{ jira_install }}/conf/server.xml"
    owner: "{{ jira_user }}"
    group: "{{ jira_user }}"
    mode: 0444

- name: enable service
  service:
    name: "jira"
    enabled: "yes"
  notify: restart jira
